[package]
name = "steelseries_screen"
version = "0.2.0"
edition = "2024"
authors = ["Max Kammler"]
license = "MIT"

[dependencies]
embedded-graphics = "0.8.1"
reqwest = { version = "0.12.22", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
